# coding: utf-8

# flake8: noqa

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AnalyticsApi",
    "CreditsApi",
    "CustomersApi",
    "DemoApi",
    "EntitlementsApi",
    "HealthApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HealthGet200Response",
    "ReadyGet200Response",
    "V1AnalyticsBurnRateGet200Response",
    "V1AnalyticsBurnRateGet200ResponseData",
    "V1AnalyticsBurnRateGet200ResponseDataLast7Days",
    "V1AnalyticsBurnRateGet200ResponseDataProjectedRunout",
    "V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner",
    "V1AnalyticsCostsGet200Response",
    "V1AnalyticsCostsGet200ResponseData",
    "V1AnalyticsCostsGet200ResponseDataByProviderInner",
    "V1AnalyticsCostsGet200ResponseDataSummary",
    "V1AnalyticsUsageGet200Response",
    "V1AnalyticsUsageGet200ResponseData",
    "V1AnalyticsUsageGet200ResponseDataByFeatureInner",
    "V1AnalyticsUsageGet200ResponseDataByProviderInner",
    "V1AnalyticsUsageGet200ResponseDataSummary",
    "V1AnalyticsUsageGet200ResponseDataTimelineInner",
    "V1CreditsBalanceGet200Response",
    "V1CreditsBalanceGet200ResponseData",
    "V1CreditsGrantPost200Response",
    "V1CreditsGrantPost200ResponseData",
    "V1CreditsGrantPost409Response",
    "V1CreditsGrantPostRequest",
    "V1CreditsPurchasePost200Response",
    "V1CreditsPurchasePost200ResponseData",
    "V1CreditsPurchasePostRequest",
    "V1CustomersCustomerIdEntitlementsGet200Response",
    "V1CustomersCustomerIdEntitlementsGet200ResponseDataInner",
    "V1CustomersCustomerIdUsersUserIdCreditsGet200Response",
    "V1CustomersCustomerIdUsersUserIdCreditsGet200ResponseData",
    "V1CustomersCustomerIdUsersUserIdTransactionsGet200Response",
    "V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponseDataInner",
    "V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponsePagination",
    "V1CustomersMeGet200Response",
    "V1CustomersMeGet200ResponseData",
    "V1CustomersRegisterPost201Response",
    "V1CustomersRegisterPost201ResponseData",
    "V1CustomersRegisterPost400Response",
    "V1CustomersRegisterPostRequest",
    "V1DemoGeneratePostRequest",
    "V1EntitlementsCheckPost200Response",
    "V1EntitlementsCheckPost200ResponseActionsInner",
    "V1EntitlementsCheckPostRequest",
    "V1EntitlementsCheckPostRequestAction",
    "V1EntitlementsIdPutRequest",
    "V1EntitlementsPost201Response",
    "V1EntitlementsPost201ResponseData",
    "V1EntitlementsPostRequest",
    "V1InfoGet200Response",
]

# import apis into sdk package
from openmonetize.api.analytics_api import AnalyticsApi as AnalyticsApi
from openmonetize.api.credits_api import CreditsApi as CreditsApi
from openmonetize.api.customers_api import CustomersApi as CustomersApi
from openmonetize.api.demo_api import DemoApi as DemoApi
from openmonetize.api.entitlements_api import EntitlementsApi as EntitlementsApi
from openmonetize.api.health_api import HealthApi as HealthApi
from openmonetize.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openmonetize.api_response import ApiResponse as ApiResponse
from openmonetize.api_client import ApiClient as ApiClient
from openmonetize.configuration import Configuration as Configuration
from openmonetize.exceptions import OpenApiException as OpenApiException
from openmonetize.exceptions import ApiTypeError as ApiTypeError
from openmonetize.exceptions import ApiValueError as ApiValueError
from openmonetize.exceptions import ApiKeyError as ApiKeyError
from openmonetize.exceptions import ApiAttributeError as ApiAttributeError
from openmonetize.exceptions import ApiException as ApiException

# import models into sdk package
from openmonetize.models.health_get200_response import HealthGet200Response as HealthGet200Response
from openmonetize.models.ready_get200_response import ReadyGet200Response as ReadyGet200Response
from openmonetize.models.v1_analytics_burn_rate_get200_response import V1AnalyticsBurnRateGet200Response as V1AnalyticsBurnRateGet200Response
from openmonetize.models.v1_analytics_burn_rate_get200_response_data import V1AnalyticsBurnRateGet200ResponseData as V1AnalyticsBurnRateGet200ResponseData
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_last7_days import V1AnalyticsBurnRateGet200ResponseDataLast7Days as V1AnalyticsBurnRateGet200ResponseDataLast7Days
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_projected_runout import V1AnalyticsBurnRateGet200ResponseDataProjectedRunout as V1AnalyticsBurnRateGet200ResponseDataProjectedRunout
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_recommendations_inner import V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner as V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner
from openmonetize.models.v1_analytics_costs_get200_response import V1AnalyticsCostsGet200Response as V1AnalyticsCostsGet200Response
from openmonetize.models.v1_analytics_costs_get200_response_data import V1AnalyticsCostsGet200ResponseData as V1AnalyticsCostsGet200ResponseData
from openmonetize.models.v1_analytics_costs_get200_response_data_by_provider_inner import V1AnalyticsCostsGet200ResponseDataByProviderInner as V1AnalyticsCostsGet200ResponseDataByProviderInner
from openmonetize.models.v1_analytics_costs_get200_response_data_summary import V1AnalyticsCostsGet200ResponseDataSummary as V1AnalyticsCostsGet200ResponseDataSummary
from openmonetize.models.v1_analytics_usage_get200_response import V1AnalyticsUsageGet200Response as V1AnalyticsUsageGet200Response
from openmonetize.models.v1_analytics_usage_get200_response_data import V1AnalyticsUsageGet200ResponseData as V1AnalyticsUsageGet200ResponseData
from openmonetize.models.v1_analytics_usage_get200_response_data_by_feature_inner import V1AnalyticsUsageGet200ResponseDataByFeatureInner as V1AnalyticsUsageGet200ResponseDataByFeatureInner
from openmonetize.models.v1_analytics_usage_get200_response_data_by_provider_inner import V1AnalyticsUsageGet200ResponseDataByProviderInner as V1AnalyticsUsageGet200ResponseDataByProviderInner
from openmonetize.models.v1_analytics_usage_get200_response_data_summary import V1AnalyticsUsageGet200ResponseDataSummary as V1AnalyticsUsageGet200ResponseDataSummary
from openmonetize.models.v1_analytics_usage_get200_response_data_timeline_inner import V1AnalyticsUsageGet200ResponseDataTimelineInner as V1AnalyticsUsageGet200ResponseDataTimelineInner
from openmonetize.models.v1_credits_balance_get200_response import V1CreditsBalanceGet200Response as V1CreditsBalanceGet200Response
from openmonetize.models.v1_credits_balance_get200_response_data import V1CreditsBalanceGet200ResponseData as V1CreditsBalanceGet200ResponseData
from openmonetize.models.v1_credits_grant_post200_response import V1CreditsGrantPost200Response as V1CreditsGrantPost200Response
from openmonetize.models.v1_credits_grant_post200_response_data import V1CreditsGrantPost200ResponseData as V1CreditsGrantPost200ResponseData
from openmonetize.models.v1_credits_grant_post409_response import V1CreditsGrantPost409Response as V1CreditsGrantPost409Response
from openmonetize.models.v1_credits_grant_post_request import V1CreditsGrantPostRequest as V1CreditsGrantPostRequest
from openmonetize.models.v1_credits_purchase_post200_response import V1CreditsPurchasePost200Response as V1CreditsPurchasePost200Response
from openmonetize.models.v1_credits_purchase_post200_response_data import V1CreditsPurchasePost200ResponseData as V1CreditsPurchasePost200ResponseData
from openmonetize.models.v1_credits_purchase_post_request import V1CreditsPurchasePostRequest as V1CreditsPurchasePostRequest
from openmonetize.models.v1_customers_customer_id_entitlements_get200_response import V1CustomersCustomerIdEntitlementsGet200Response as V1CustomersCustomerIdEntitlementsGet200Response
from openmonetize.models.v1_customers_customer_id_entitlements_get200_response_data_inner import V1CustomersCustomerIdEntitlementsGet200ResponseDataInner as V1CustomersCustomerIdEntitlementsGet200ResponseDataInner
from openmonetize.models.v1_customers_customer_id_users_user_id_credits_get200_response import V1CustomersCustomerIdUsersUserIdCreditsGet200Response as V1CustomersCustomerIdUsersUserIdCreditsGet200Response
from openmonetize.models.v1_customers_customer_id_users_user_id_credits_get200_response_data import V1CustomersCustomerIdUsersUserIdCreditsGet200ResponseData as V1CustomersCustomerIdUsersUserIdCreditsGet200ResponseData
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response import V1CustomersCustomerIdUsersUserIdTransactionsGet200Response as V1CustomersCustomerIdUsersUserIdTransactionsGet200Response
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response_data_inner import V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponseDataInner as V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponseDataInner
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response_pagination import V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponsePagination as V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponsePagination
from openmonetize.models.v1_customers_me_get200_response import V1CustomersMeGet200Response as V1CustomersMeGet200Response
from openmonetize.models.v1_customers_me_get200_response_data import V1CustomersMeGet200ResponseData as V1CustomersMeGet200ResponseData
from openmonetize.models.v1_customers_register_post201_response import V1CustomersRegisterPost201Response as V1CustomersRegisterPost201Response
from openmonetize.models.v1_customers_register_post201_response_data import V1CustomersRegisterPost201ResponseData as V1CustomersRegisterPost201ResponseData
from openmonetize.models.v1_customers_register_post400_response import V1CustomersRegisterPost400Response as V1CustomersRegisterPost400Response
from openmonetize.models.v1_customers_register_post_request import V1CustomersRegisterPostRequest as V1CustomersRegisterPostRequest
from openmonetize.models.v1_demo_generate_post_request import V1DemoGeneratePostRequest as V1DemoGeneratePostRequest
from openmonetize.models.v1_entitlements_check_post200_response import V1EntitlementsCheckPost200Response as V1EntitlementsCheckPost200Response
from openmonetize.models.v1_entitlements_check_post200_response_actions_inner import V1EntitlementsCheckPost200ResponseActionsInner as V1EntitlementsCheckPost200ResponseActionsInner
from openmonetize.models.v1_entitlements_check_post_request import V1EntitlementsCheckPostRequest as V1EntitlementsCheckPostRequest
from openmonetize.models.v1_entitlements_check_post_request_action import V1EntitlementsCheckPostRequestAction as V1EntitlementsCheckPostRequestAction
from openmonetize.models.v1_entitlements_id_put_request import V1EntitlementsIdPutRequest as V1EntitlementsIdPutRequest
from openmonetize.models.v1_entitlements_post201_response import V1EntitlementsPost201Response as V1EntitlementsPost201Response
from openmonetize.models.v1_entitlements_post201_response_data import V1EntitlementsPost201ResponseData as V1EntitlementsPost201ResponseData
from openmonetize.models.v1_entitlements_post_request import V1EntitlementsPostRequest as V1EntitlementsPostRequest
from openmonetize.models.v1_info_get200_response import V1InfoGet200Response as V1InfoGet200Response

