# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure
"""

from openmonetize.api_client import ApiClient

class DefaultApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client
