# coding: utf-8
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.api.entitlements_api import EntitlementsApi


class TestEntitlementsApi(unittest.TestCase):
    """EntitlementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntitlementsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_customers_customer_id_entitlements_get(self) -> None:
        """Test case for v1_customers_customer_id_entitlements_get

        """
        pass

    def test_v1_entitlements_check_post(self) -> None:
        """Test case for v1_entitlements_check_post

        """
        pass

    def test_v1_entitlements_id_delete(self) -> None:
        """Test case for v1_entitlements_id_delete

        """
        pass

    def test_v1_entitlements_id_put(self) -> None:
        """Test case for v1_entitlements_id_put

        """
        pass

    def test_v1_entitlements_post(self) -> None:
        """Test case for v1_entitlements_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
