# coding: utf-8
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_analytics_burn_rate_get200_response import V1AnalyticsBurnRateGet200Response

class TestV1AnalyticsBurnRateGet200Response(unittest.TestCase):
    """V1AnalyticsBurnRateGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AnalyticsBurnRateGet200Response:
        """Test V1AnalyticsBurnRateGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AnalyticsBurnRateGet200Response`
        """
        model = V1AnalyticsBurnRateGet200Response()
        if include_optional:
            return V1AnalyticsBurnRateGet200Response(
                data = openmonetize.models._v1_analytics_burn_rate_get_200_response_data._v1_analytics_burn_rate_get_200_response_data(
                    current_balance = '', 
                    last7_days = openmonetize.models._v1_analytics_burn_rate_get_200_response_data_last7_days._v1_analytics_burn_rate_get_200_response_data_last7Days(
                        credits_burned = '', 
                        average_per_day = '', ), 
                    last30_days = openmonetize.models._v1_analytics_burn_rate_get_200_response_data_last7_days._v1_analytics_burn_rate_get_200_response_data_last7Days(
                        credits_burned = '', 
                        average_per_day = '', ), 
                    projected_runout = openmonetize.models._v1_analytics_burn_rate_get_200_response_data_projected_runout._v1_analytics_burn_rate_get_200_response_data_projectedRunout(
                        days_remaining = 1.337, 
                        estimated_runout_date = '', ), 
                    recommendations = [
                        openmonetize.models._v1_analytics_burn_rate_get_200_response_data_recommendations_inner._v1_analytics_burn_rate_get_200_response_data_recommendations_inner(
                            type = '', 
                            message = '', 
                            action = '', )
                        ], )
            )
        else:
            return V1AnalyticsBurnRateGet200Response(
        )
        """

    def testV1AnalyticsBurnRateGet200Response(self):
        """Test V1AnalyticsBurnRateGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
