# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_analytics_usage_get200_response_data import V1AnalyticsUsageGet200ResponseData

class TestV1AnalyticsUsageGet200ResponseData(unittest.TestCase):
    """V1AnalyticsUsageGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AnalyticsUsageGet200ResponseData:
        """Test V1AnalyticsUsageGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AnalyticsUsageGet200ResponseData`
        """
        model = V1AnalyticsUsageGet200ResponseData()
        if include_optional:
            return V1AnalyticsUsageGet200ResponseData(
                summary = openmonetize.models._v1_analytics_usage_get_200_response_data_summary._v1_analytics_usage_get_200_response_data_summary(
                    total_events = 1.337, 
                    total_input_tokens = '', 
                    total_output_tokens = '', 
                    total_credits_burned = '', 
                    total_cost_usd = '', ),
                by_feature = [
                    openmonetize.models._v1_analytics_usage_get_200_response_data_by_feature_inner._v1_analytics_usage_get_200_response_data_byFeature_inner(
                        feature_id = '', 
                        event_count = 1.337, 
                        credits_burned = '', 
                        cost_usd = '', )
                    ],
                by_provider = [
                    openmonetize.models._v1_analytics_usage_get_200_response_data_by_provider_inner._v1_analytics_usage_get_200_response_data_byProvider_inner(
                        provider = '', 
                        model = '', 
                        event_count = 1.337, 
                        input_tokens = '', 
                        output_tokens = '', )
                    ],
                timeline = [
                    openmonetize.models._v1_analytics_usage_get_200_response_data_timeline_inner._v1_analytics_usage_get_200_response_data_timeline_inner(
                        date = '', 
                        events = 1.337, 
                        credits_burned = '', )
                    ]
            )
        else:
            return V1AnalyticsUsageGet200ResponseData(
        )
        """

    def testV1AnalyticsUsageGet200ResponseData(self):
        """Test V1AnalyticsUsageGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
