# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_customers_customer_id_users_user_id_credits_get200_response import V1CustomersCustomerIdUsersUserIdCreditsGet200Response

class TestV1CustomersCustomerIdUsersUserIdCreditsGet200Response(unittest.TestCase):
    """V1CustomersCustomerIdUsersUserIdCreditsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CustomersCustomerIdUsersUserIdCreditsGet200Response:
        """Test V1CustomersCustomerIdUsersUserIdCreditsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CustomersCustomerIdUsersUserIdCreditsGet200Response`
        """
        model = V1CustomersCustomerIdUsersUserIdCreditsGet200Response()
        if include_optional:
            return V1CustomersCustomerIdUsersUserIdCreditsGet200Response(
                data = openmonetize.models._v1_customers__customer_id__users__user_id__credits_get_200_response_data._v1_customers__customerId__users__userId__credits_get_200_response_data(
                    balance = 1.337, 
                    reserved = 1.337, 
                    available = 1.337, 
                    expires_at = '', )
            )
        else:
            return V1CustomersCustomerIdUsersUserIdCreditsGet200Response(
        )
        """

    def testV1CustomersCustomerIdUsersUserIdCreditsGet200Response(self):
        """Test V1CustomersCustomerIdUsersUserIdCreditsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
