# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v1_analytics_delete(self) -> None:
        """Test case for v1_analytics_delete

        """
        pass

    def test_v1_analytics_delete_0(self) -> None:
        """Test case for v1_analytics_delete_0

        """
        pass

    def test_v1_analytics_get(self) -> None:
        """Test case for v1_analytics_get

        """
        pass

    def test_v1_analytics_get_0(self) -> None:
        """Test case for v1_analytics_get_0

        """
        pass

    def test_v1_analytics_head(self) -> None:
        """Test case for v1_analytics_head

        """
        pass

    def test_v1_analytics_head_0(self) -> None:
        """Test case for v1_analytics_head_0

        """
        pass

    def test_v1_analytics_options(self) -> None:
        """Test case for v1_analytics_options

        """
        pass

    def test_v1_analytics_options_0(self) -> None:
        """Test case for v1_analytics_options_0

        """
        pass

    def test_v1_analytics_patch(self) -> None:
        """Test case for v1_analytics_patch

        """
        pass

    def test_v1_analytics_patch_0(self) -> None:
        """Test case for v1_analytics_patch_0

        """
        pass

    def test_v1_analytics_post(self) -> None:
        """Test case for v1_analytics_post

        """
        pass

    def test_v1_analytics_post_0(self) -> None:
        """Test case for v1_analytics_post_0

        """
        pass

    def test_v1_analytics_put(self) -> None:
        """Test case for v1_analytics_put

        """
        pass

    def test_v1_analytics_put_0(self) -> None:
        """Test case for v1_analytics_put_0

        """
        pass

    def test_v1_burn_tables_delete(self) -> None:
        """Test case for v1_burn_tables_delete

        """
        pass

    def test_v1_burn_tables_delete_0(self) -> None:
        """Test case for v1_burn_tables_delete_0

        """
        pass

    def test_v1_burn_tables_get(self) -> None:
        """Test case for v1_burn_tables_get

        """
        pass

    def test_v1_burn_tables_get_0(self) -> None:
        """Test case for v1_burn_tables_get_0

        """
        pass

    def test_v1_burn_tables_head(self) -> None:
        """Test case for v1_burn_tables_head

        """
        pass

    def test_v1_burn_tables_head_0(self) -> None:
        """Test case for v1_burn_tables_head_0

        """
        pass

    def test_v1_burn_tables_options(self) -> None:
        """Test case for v1_burn_tables_options

        """
        pass

    def test_v1_burn_tables_options_0(self) -> None:
        """Test case for v1_burn_tables_options_0

        """
        pass

    def test_v1_burn_tables_patch(self) -> None:
        """Test case for v1_burn_tables_patch

        """
        pass

    def test_v1_burn_tables_patch_0(self) -> None:
        """Test case for v1_burn_tables_patch_0

        """
        pass

    def test_v1_burn_tables_post(self) -> None:
        """Test case for v1_burn_tables_post

        """
        pass

    def test_v1_burn_tables_post_0(self) -> None:
        """Test case for v1_burn_tables_post_0

        """
        pass

    def test_v1_burn_tables_put(self) -> None:
        """Test case for v1_burn_tables_put

        """
        pass

    def test_v1_burn_tables_put_0(self) -> None:
        """Test case for v1_burn_tables_put_0

        """
        pass

    def test_v1_events_delete(self) -> None:
        """Test case for v1_events_delete

        """
        pass

    def test_v1_events_delete_0(self) -> None:
        """Test case for v1_events_delete_0

        """
        pass

    def test_v1_events_get(self) -> None:
        """Test case for v1_events_get

        """
        pass

    def test_v1_events_get_0(self) -> None:
        """Test case for v1_events_get_0

        """
        pass

    def test_v1_events_head(self) -> None:
        """Test case for v1_events_head

        """
        pass

    def test_v1_events_head_0(self) -> None:
        """Test case for v1_events_head_0

        """
        pass

    def test_v1_events_options(self) -> None:
        """Test case for v1_events_options

        """
        pass

    def test_v1_events_options_0(self) -> None:
        """Test case for v1_events_options_0

        """
        pass

    def test_v1_events_patch(self) -> None:
        """Test case for v1_events_patch

        """
        pass

    def test_v1_events_patch_0(self) -> None:
        """Test case for v1_events_patch_0

        """
        pass

    def test_v1_events_post(self) -> None:
        """Test case for v1_events_post

        """
        pass

    def test_v1_events_post_0(self) -> None:
        """Test case for v1_events_post_0

        """
        pass

    def test_v1_events_put(self) -> None:
        """Test case for v1_events_put

        """
        pass

    def test_v1_events_put_0(self) -> None:
        """Test case for v1_events_put_0

        """
        pass

    def test_v1_rating_delete(self) -> None:
        """Test case for v1_rating_delete

        """
        pass

    def test_v1_rating_delete_0(self) -> None:
        """Test case for v1_rating_delete_0

        """
        pass

    def test_v1_rating_get(self) -> None:
        """Test case for v1_rating_get

        """
        pass

    def test_v1_rating_get_0(self) -> None:
        """Test case for v1_rating_get_0

        """
        pass

    def test_v1_rating_head(self) -> None:
        """Test case for v1_rating_head

        """
        pass

    def test_v1_rating_head_0(self) -> None:
        """Test case for v1_rating_head_0

        """
        pass

    def test_v1_rating_options(self) -> None:
        """Test case for v1_rating_options

        """
        pass

    def test_v1_rating_options_0(self) -> None:
        """Test case for v1_rating_options_0

        """
        pass

    def test_v1_rating_patch(self) -> None:
        """Test case for v1_rating_patch

        """
        pass

    def test_v1_rating_patch_0(self) -> None:
        """Test case for v1_rating_patch_0

        """
        pass

    def test_v1_rating_post(self) -> None:
        """Test case for v1_rating_post

        """
        pass

    def test_v1_rating_post_0(self) -> None:
        """Test case for v1_rating_post_0

        """
        pass

    def test_v1_rating_put(self) -> None:
        """Test case for v1_rating_put

        """
        pass

    def test_v1_rating_put_0(self) -> None:
        """Test case for v1_rating_put_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
