# coding: utf-8
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_analytics_usage_get200_response_data_summary import V1AnalyticsUsageGet200ResponseDataSummary

class TestV1AnalyticsUsageGet200ResponseDataSummary(unittest.TestCase):
    """V1AnalyticsUsageGet200ResponseDataSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AnalyticsUsageGet200ResponseDataSummary:
        """Test V1AnalyticsUsageGet200ResponseDataSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AnalyticsUsageGet200ResponseDataSummary`
        """
        model = V1AnalyticsUsageGet200ResponseDataSummary()
        if include_optional:
            return V1AnalyticsUsageGet200ResponseDataSummary(
                total_events = 1.337,
                total_input_tokens = '',
                total_output_tokens = '',
                total_credits_burned = '',
                total_cost_usd = ''
            )
        else:
            return V1AnalyticsUsageGet200ResponseDataSummary(
        )
        """

    def testV1AnalyticsUsageGet200ResponseDataSummary(self):
        """Test V1AnalyticsUsageGet200ResponseDataSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
