# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_entitlements_check_post_request_action import V1EntitlementsCheckPostRequestAction

class TestV1EntitlementsCheckPostRequestAction(unittest.TestCase):
    """V1EntitlementsCheckPostRequestAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EntitlementsCheckPostRequestAction:
        """Test V1EntitlementsCheckPostRequestAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EntitlementsCheckPostRequestAction`
        """
        model = V1EntitlementsCheckPostRequestAction()
        if include_optional:
            return V1EntitlementsCheckPostRequestAction(
                type = 'token_usage',
                provider = '',
                model = '',
                estimated_input_tokens = 1.337,
                estimated_output_tokens = 1.337
            )
        else:
            return V1EntitlementsCheckPostRequestAction(
                type = 'token_usage',
        )
        """

    def testV1EntitlementsCheckPostRequestAction(self):
        """Test V1EntitlementsCheckPostRequestAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
