# coding: utf-8
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.api.credits_api import CreditsApi


class TestCreditsApi(unittest.TestCase):
    """CreditsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_credits_balance_get(self) -> None:
        """Test case for v1_credits_balance_get

        """
        pass

    def test_v1_credits_grant_post(self) -> None:
        """Test case for v1_credits_grant_post

        """
        pass

    def test_v1_credits_purchase_post(self) -> None:
        """Test case for v1_credits_purchase_post

        """
        pass

    def test_v1_customers_customer_id_users_user_id_credits_get(self) -> None:
        """Test case for v1_customers_customer_id_users_user_id_credits_get

        """
        pass

    def test_v1_customers_customer_id_users_user_id_transactions_get(self) -> None:
        """Test case for v1_customers_customer_id_users_user_id_transactions_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
