# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_customers_register_post201_response import V1CustomersRegisterPost201Response

class TestV1CustomersRegisterPost201Response(unittest.TestCase):
    """V1CustomersRegisterPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CustomersRegisterPost201Response:
        """Test V1CustomersRegisterPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CustomersRegisterPost201Response`
        """
        model = V1CustomersRegisterPost201Response()
        if include_optional:
            return V1CustomersRegisterPost201Response(
                data = openmonetize.models._v1_customers_register_post_201_response_data._v1_customers_register_post_201_response_data(
                    customer_id = '', 
                    api_key = '', 
                    name = '', 
                    email = '', 
                    tier = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1CustomersRegisterPost201Response(
        )
        """

    def testV1CustomersRegisterPost201Response(self):
        """Test V1CustomersRegisterPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
