# coding: utf-8
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_analytics_costs_get200_response_data_summary import V1AnalyticsCostsGet200ResponseDataSummary

class TestV1AnalyticsCostsGet200ResponseDataSummary(unittest.TestCase):
    """V1AnalyticsCostsGet200ResponseDataSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AnalyticsCostsGet200ResponseDataSummary:
        """Test V1AnalyticsCostsGet200ResponseDataSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AnalyticsCostsGet200ResponseDataSummary`
        """
        model = V1AnalyticsCostsGet200ResponseDataSummary()
        if include_optional:
            return V1AnalyticsCostsGet200ResponseDataSummary(
                total_revenue = '',
                total_provider_cost = '',
                total_margin = '',
                margin_percent = 1.337
            )
        else:
            return V1AnalyticsCostsGet200ResponseDataSummary(
        )
        """

    def testV1AnalyticsCostsGet200ResponseDataSummary(self):
        """Test V1AnalyticsCostsGet200ResponseDataSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
