# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_entitlements_check_post200_response_actions_inner import V1EntitlementsCheckPost200ResponseActionsInner

class TestV1EntitlementsCheckPost200ResponseActionsInner(unittest.TestCase):
    """V1EntitlementsCheckPost200ResponseActionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EntitlementsCheckPost200ResponseActionsInner:
        """Test V1EntitlementsCheckPost200ResponseActionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EntitlementsCheckPost200ResponseActionsInner`
        """
        model = V1EntitlementsCheckPost200ResponseActionsInner()
        if include_optional:
            return V1EntitlementsCheckPost200ResponseActionsInner(
                type = '',
                label = '',
                url = ''
            )
        else:
            return V1EntitlementsCheckPost200ResponseActionsInner(
        )
        """

    def testV1EntitlementsCheckPost200ResponseActionsInner(self):
        """Test V1EntitlementsCheckPost200ResponseActionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
