# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openmonetize.models.v1_demo_generate_post_request import V1DemoGeneratePostRequest

class TestV1DemoGeneratePostRequest(unittest.TestCase):
    """V1DemoGeneratePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DemoGeneratePostRequest:
        """Test V1DemoGeneratePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DemoGeneratePostRequest`
        """
        model = V1DemoGeneratePostRequest()
        if include_optional:
            return V1DemoGeneratePostRequest(
                prompt = '',
                model = '',
                provider = ''
            )
        else:
            return V1DemoGeneratePostRequest(
                prompt = '',
        )
        """

    def testV1DemoGeneratePostRequest(self):
        """Test V1DemoGeneratePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
