# coding: utf-8

# Copyright (C) 2025 OpenMonetize
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# flake8: noqa
"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openmonetize.models.health_get200_response import HealthGet200Response
from openmonetize.models.ready_get200_response import ReadyGet200Response
from openmonetize.models.v1_analytics_burn_rate_get200_response import V1AnalyticsBurnRateGet200Response
from openmonetize.models.v1_analytics_burn_rate_get200_response_data import V1AnalyticsBurnRateGet200ResponseData
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_last7_days import V1AnalyticsBurnRateGet200ResponseDataLast7Days
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_projected_runout import V1AnalyticsBurnRateGet200ResponseDataProjectedRunout
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_recommendations_inner import V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner
from openmonetize.models.v1_analytics_costs_get200_response import V1AnalyticsCostsGet200Response
from openmonetize.models.v1_analytics_costs_get200_response_data import V1AnalyticsCostsGet200ResponseData
from openmonetize.models.v1_analytics_costs_get200_response_data_by_provider_inner import V1AnalyticsCostsGet200ResponseDataByProviderInner
from openmonetize.models.v1_analytics_costs_get200_response_data_summary import V1AnalyticsCostsGet200ResponseDataSummary
from openmonetize.models.v1_analytics_usage_get200_response import V1AnalyticsUsageGet200Response
from openmonetize.models.v1_analytics_usage_get200_response_data import V1AnalyticsUsageGet200ResponseData
from openmonetize.models.v1_analytics_usage_get200_response_data_by_feature_inner import V1AnalyticsUsageGet200ResponseDataByFeatureInner
from openmonetize.models.v1_analytics_usage_get200_response_data_by_provider_inner import V1AnalyticsUsageGet200ResponseDataByProviderInner
from openmonetize.models.v1_analytics_usage_get200_response_data_summary import V1AnalyticsUsageGet200ResponseDataSummary
from openmonetize.models.v1_analytics_usage_get200_response_data_timeline_inner import V1AnalyticsUsageGet200ResponseDataTimelineInner
from openmonetize.models.v1_credits_balance_get200_response import V1CreditsBalanceGet200Response
from openmonetize.models.v1_credits_balance_get200_response_data import V1CreditsBalanceGet200ResponseData
from openmonetize.models.v1_credits_grant_post200_response import V1CreditsGrantPost200Response
from openmonetize.models.v1_credits_grant_post200_response_data import V1CreditsGrantPost200ResponseData
from openmonetize.models.v1_credits_grant_post409_response import V1CreditsGrantPost409Response
from openmonetize.models.v1_credits_grant_post_request import V1CreditsGrantPostRequest
from openmonetize.models.v1_credits_purchase_post200_response import V1CreditsPurchasePost200Response
from openmonetize.models.v1_credits_purchase_post200_response_data import V1CreditsPurchasePost200ResponseData
from openmonetize.models.v1_credits_purchase_post_request import V1CreditsPurchasePostRequest
from openmonetize.models.v1_customers_customer_id_entitlements_get200_response import V1CustomersCustomerIdEntitlementsGet200Response
from openmonetize.models.v1_customers_customer_id_entitlements_get200_response_data_inner import V1CustomersCustomerIdEntitlementsGet200ResponseDataInner
from openmonetize.models.v1_customers_customer_id_users_user_id_credits_get200_response import V1CustomersCustomerIdUsersUserIdCreditsGet200Response
from openmonetize.models.v1_customers_customer_id_users_user_id_credits_get200_response_data import V1CustomersCustomerIdUsersUserIdCreditsGet200ResponseData
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response import V1CustomersCustomerIdUsersUserIdTransactionsGet200Response
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response_data_inner import V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponseDataInner
from openmonetize.models.v1_customers_customer_id_users_user_id_transactions_get200_response_pagination import V1CustomersCustomerIdUsersUserIdTransactionsGet200ResponsePagination
from openmonetize.models.v1_customers_me_get200_response import V1CustomersMeGet200Response
from openmonetize.models.v1_customers_me_get200_response_data import V1CustomersMeGet200ResponseData
from openmonetize.models.v1_customers_register_post201_response import V1CustomersRegisterPost201Response
from openmonetize.models.v1_customers_register_post201_response_data import V1CustomersRegisterPost201ResponseData
from openmonetize.models.v1_customers_register_post400_response import V1CustomersRegisterPost400Response
from openmonetize.models.v1_customers_register_post_request import V1CustomersRegisterPostRequest
from openmonetize.models.v1_demo_generate_post_request import V1DemoGeneratePostRequest
from openmonetize.models.v1_entitlements_check_post200_response import V1EntitlementsCheckPost200Response
from openmonetize.models.v1_entitlements_check_post200_response_actions_inner import V1EntitlementsCheckPost200ResponseActionsInner
from openmonetize.models.v1_entitlements_check_post_request import V1EntitlementsCheckPostRequest
from openmonetize.models.v1_entitlements_check_post_request_action import V1EntitlementsCheckPostRequestAction
from openmonetize.models.v1_entitlements_id_put_request import V1EntitlementsIdPutRequest
from openmonetize.models.v1_entitlements_post201_response import V1EntitlementsPost201Response
from openmonetize.models.v1_entitlements_post201_response_data import V1EntitlementsPost201ResponseData
from openmonetize.models.v1_entitlements_post_request import V1EntitlementsPostRequest
from openmonetize.models.v1_info_get200_response import V1InfoGet200Response as V1InfoGet200Response
from openmonetize.models.custom_event import CustomEvent as CustomEvent
from openmonetize.models.image_generation_event import ImageGenerationEvent as ImageGenerationEvent
from openmonetize.models.token_usage_event import TokenUsageEvent as TokenUsageEvent
