# coding: utf-8

# Copyright (C) 2025 OpenMonetize
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_last7_days import V1AnalyticsBurnRateGet200ResponseDataLast7Days
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_projected_runout import V1AnalyticsBurnRateGet200ResponseDataProjectedRunout
from openmonetize.models.v1_analytics_burn_rate_get200_response_data_recommendations_inner import V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner
from typing import Optional, Set
from typing_extensions import Self

class V1AnalyticsBurnRateGet200ResponseData(BaseModel):
    """
    V1AnalyticsBurnRateGet200ResponseData
    """ # noqa: E501
    current_balance: Optional[StrictStr] = Field(default=None, alias="currentBalance")
    last7_days: Optional[V1AnalyticsBurnRateGet200ResponseDataLast7Days] = Field(default=None, alias="last7Days")
    last30_days: Optional[V1AnalyticsBurnRateGet200ResponseDataLast7Days] = Field(default=None, alias="last30Days")
    projected_runout: Optional[V1AnalyticsBurnRateGet200ResponseDataProjectedRunout] = Field(default=None, alias="projectedRunout")
    recommendations: Optional[List[V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner]] = None
    __properties: ClassVar[List[str]] = ["currentBalance", "last7Days", "last30Days", "projectedRunout", "recommendations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AnalyticsBurnRateGet200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last7_days
        if self.last7_days:
            _dict['last7Days'] = self.last7_days.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last30_days
        if self.last30_days:
            _dict['last30Days'] = self.last30_days.to_dict()
        # override the default output from pydantic by calling `to_dict()` of projected_runout
        if self.projected_runout:
            _dict['projectedRunout'] = self.projected_runout.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recommendations (list)
        _items = []
        if self.recommendations:
            for _item_recommendations in self.recommendations:
                if _item_recommendations:
                    _items.append(_item_recommendations.to_dict())
            _dict['recommendations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AnalyticsBurnRateGet200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currentBalance": obj.get("currentBalance"),
            "last7Days": V1AnalyticsBurnRateGet200ResponseDataLast7Days.from_dict(obj["last7Days"]) if obj.get("last7Days") is not None else None,
            "last30Days": V1AnalyticsBurnRateGet200ResponseDataLast7Days.from_dict(obj["last30Days"]) if obj.get("last30Days") is not None else None,
            "projectedRunout": V1AnalyticsBurnRateGet200ResponseDataProjectedRunout.from_dict(obj["projectedRunout"]) if obj.get("projectedRunout") is not None else None,
            "recommendations": [V1AnalyticsBurnRateGet200ResponseDataRecommendationsInner.from_dict(_item) for _item in obj["recommendations"]] if obj.get("recommendations") is not None else None
        })
        return _obj


