# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openmonetize.models.v1_analytics_usage_get200_response_data_by_feature_inner import V1AnalyticsUsageGet200ResponseDataByFeatureInner
from openmonetize.models.v1_analytics_usage_get200_response_data_by_provider_inner import V1AnalyticsUsageGet200ResponseDataByProviderInner
from openmonetize.models.v1_analytics_usage_get200_response_data_summary import V1AnalyticsUsageGet200ResponseDataSummary
from openmonetize.models.v1_analytics_usage_get200_response_data_timeline_inner import V1AnalyticsUsageGet200ResponseDataTimelineInner
from typing import Optional, Set
from typing_extensions import Self

class V1AnalyticsUsageGet200ResponseData(BaseModel):
    """
    V1AnalyticsUsageGet200ResponseData
    """ # noqa: E501
    summary: Optional[V1AnalyticsUsageGet200ResponseDataSummary] = None
    by_feature: Optional[List[V1AnalyticsUsageGet200ResponseDataByFeatureInner]] = Field(default=None, alias="byFeature")
    by_provider: Optional[List[V1AnalyticsUsageGet200ResponseDataByProviderInner]] = Field(default=None, alias="byProvider")
    timeline: Optional[List[V1AnalyticsUsageGet200ResponseDataTimelineInner]] = None
    __properties: ClassVar[List[str]] = ["summary", "byFeature", "byProvider", "timeline"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1AnalyticsUsageGet200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in by_feature (list)
        _items = []
        if self.by_feature:
            for _item_by_feature in self.by_feature:
                if _item_by_feature:
                    _items.append(_item_by_feature.to_dict())
            _dict['byFeature'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in by_provider (list)
        _items = []
        if self.by_provider:
            for _item_by_provider in self.by_provider:
                if _item_by_provider:
                    _items.append(_item_by_provider.to_dict())
            _dict['byProvider'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in timeline (list)
        _items = []
        if self.timeline:
            for _item_timeline in self.timeline:
                if _item_timeline:
                    _items.append(_item_timeline.to_dict())
            _dict['timeline'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1AnalyticsUsageGet200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "summary": V1AnalyticsUsageGet200ResponseDataSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "byFeature": [V1AnalyticsUsageGet200ResponseDataByFeatureInner.from_dict(_item) for _item in obj["byFeature"]] if obj.get("byFeature") is not None else None,
            "byProvider": [V1AnalyticsUsageGet200ResponseDataByProviderInner.from_dict(_item) for _item in obj["byProvider"]] if obj.get("byProvider") is not None else None,
            "timeline": [V1AnalyticsUsageGet200ResponseDataTimelineInner.from_dict(_item) for _item in obj["timeline"]] if obj.get("timeline") is not None else None
        })
        return _obj


