# coding: utf-8

# Copyright (C) 2025 OpenMonetize
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openmonetize.models.v1_entitlements_check_post200_response_actions_inner import V1EntitlementsCheckPost200ResponseActionsInner
from typing import Optional, Set
from typing_extensions import Self

class V1EntitlementsCheckPost200Response(BaseModel):
    """
    V1EntitlementsCheckPost200Response
    """ # noqa: E501
    allowed: Optional[StrictBool] = None
    reason: Optional[StrictStr] = None
    estimated_cost_credits: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="estimatedCostCredits")
    estimated_cost_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="estimatedCostUsd")
    current_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="currentBalance")
    actions: Optional[List[V1EntitlementsCheckPost200ResponseActionsInner]] = None
    __properties: ClassVar[List[str]] = ["allowed", "reason", "estimatedCostCredits", "estimatedCostUsd", "currentBalance", "actions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1EntitlementsCheckPost200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if estimated_cost_credits (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_cost_credits is None and "estimated_cost_credits" in self.model_fields_set:
            _dict['estimatedCostCredits'] = None

        # set to None if estimated_cost_usd (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_cost_usd is None and "estimated_cost_usd" in self.model_fields_set:
            _dict['estimatedCostUsd'] = None

        # set to None if current_balance (nullable) is None
        # and model_fields_set contains the field
        if self.current_balance is None and "current_balance" in self.model_fields_set:
            _dict['currentBalance'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1EntitlementsCheckPost200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed": obj.get("allowed"),
            "reason": obj.get("reason"),
            "estimatedCostCredits": obj.get("estimatedCostCredits"),
            "estimatedCostUsd": obj.get("estimatedCostUsd"),
            "currentBalance": obj.get("currentBalance"),
            "actions": [V1EntitlementsCheckPost200ResponseActionsInner.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None
        })
        return _obj


