# coding: utf-8

"""
    OpenMonetize API

    Open-source AI monetization infrastructure  ## ⚠️ Important: About \"default\" Category  The **\"default\"** section at the bottom contains HTTP proxy infrastructure routes (wildcards for all HTTP methods). These are automatically generated by the API Gateway's proxy layer and **should be ignored**.  **Instead, use the specific endpoints documented in each category above.** Only the endpoints explicitly listed in the category descriptions are actually implemented.  ## Authentication  All API endpoints require authentication using Bearer token format:  ``` Authorization: Bearer YOUR_API_KEY ```  Or using the X-API-Key header:  ``` X-API-Key: YOUR_API_KEY ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class V1EntitlementsPostRequest(BaseModel):
    """
    V1EntitlementsPostRequest
    """ # noqa: E501
    customer_id: UUID = Field(alias="customerId")
    user_id: Optional[UUID] = Field(default=None, alias="userId")
    feature_id: StrictStr = Field(alias="featureId")
    limit_type: StrictStr = Field(alias="limitType")
    limit_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="limitValue")
    period: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["customerId", "userId", "featureId", "limitType", "limitValue", "period", "metadata"]

    @field_validator('limit_type')
    def limit_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['HARD', 'SOFT', 'NONE']):
            raise ValueError("must be one of enum values ('HARD', 'SOFT', 'NONE')")
        return value

    @field_validator('period')
    def period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DAILY', 'MONTHLY', 'TOTAL']):
            raise ValueError("must be one of enum values ('DAILY', 'MONTHLY', 'TOTAL')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1EntitlementsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if limit_value (nullable) is None
        # and model_fields_set contains the field
        if self.limit_value is None and "limit_value" in self.model_fields_set:
            _dict['limitValue'] = None

        # set to None if period (nullable) is None
        # and model_fields_set contains the field
        if self.period is None and "period" in self.model_fields_set:
            _dict['period'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1EntitlementsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customerId": obj.get("customerId"),
            "userId": obj.get("userId"),
            "featureId": obj.get("featureId"),
            "limitType": obj.get("limitType"),
            "limitValue": obj.get("limitValue"),
            "period": obj.get("period"),
            "metadata": obj.get("metadata")
        })
        return _obj


