import { z } from 'zod';
import { EventType, ProviderName } from '../types';
export declare const providerNameSchema: z.ZodEnum<typeof ProviderName>;
export declare const eventTypeSchema: z.ZodEnum<typeof EventType>;
export declare const tokenUsageEventSchema: z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.TOKEN_USAGE>;
    feature_id: z.ZodString;
    provider: z.ZodEnum<typeof ProviderName>;
    model: z.ZodString;
    input_tokens: z.ZodNumber;
    output_tokens: z.ZodNumber;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const imageGenerationEventSchema: z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.IMAGE_GENERATION>;
    feature_id: z.ZodString;
    provider: z.ZodEnum<typeof ProviderName>;
    model: z.ZodString;
    resolution: z.ZodOptional<z.ZodString>;
    count: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const customEventSchema: z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.CUSTOM>;
    feature_id: z.ZodString;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const usageEventSchema: z.ZodDiscriminatedUnion<[z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.TOKEN_USAGE>;
    feature_id: z.ZodString;
    provider: z.ZodEnum<typeof ProviderName>;
    model: z.ZodString;
    input_tokens: z.ZodNumber;
    output_tokens: z.ZodNumber;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>, z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.IMAGE_GENERATION>;
    feature_id: z.ZodString;
    provider: z.ZodEnum<typeof ProviderName>;
    model: z.ZodString;
    resolution: z.ZodOptional<z.ZodString>;
    count: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>, z.ZodObject<{
    event_id: z.ZodString;
    customer_id: z.ZodString;
    user_id: z.ZodOptional<z.ZodString>;
    team_id: z.ZodOptional<z.ZodString>;
    event_type: z.ZodLiteral<EventType.CUSTOM>;
    feature_id: z.ZodString;
    timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
    metadata: z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>;
    idempotency_key: z.ZodOptional<z.ZodString>;
}, z.core.$strip>], "event_type">;
export declare const usageEventBatchSchema: z.ZodObject<{
    events: z.ZodArray<z.ZodDiscriminatedUnion<[z.ZodObject<{
        event_id: z.ZodString;
        customer_id: z.ZodString;
        user_id: z.ZodOptional<z.ZodString>;
        team_id: z.ZodOptional<z.ZodString>;
        event_type: z.ZodLiteral<EventType.TOKEN_USAGE>;
        feature_id: z.ZodString;
        provider: z.ZodEnum<typeof ProviderName>;
        model: z.ZodString;
        input_tokens: z.ZodNumber;
        output_tokens: z.ZodNumber;
        timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
        metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
        idempotency_key: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>, z.ZodObject<{
        event_id: z.ZodString;
        customer_id: z.ZodString;
        user_id: z.ZodOptional<z.ZodString>;
        team_id: z.ZodOptional<z.ZodString>;
        event_type: z.ZodLiteral<EventType.IMAGE_GENERATION>;
        feature_id: z.ZodString;
        provider: z.ZodEnum<typeof ProviderName>;
        model: z.ZodString;
        resolution: z.ZodOptional<z.ZodString>;
        count: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
        timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
        metadata: z.ZodOptional<z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>>;
        idempotency_key: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>, z.ZodObject<{
        event_id: z.ZodString;
        customer_id: z.ZodString;
        user_id: z.ZodOptional<z.ZodString>;
        team_id: z.ZodOptional<z.ZodString>;
        event_type: z.ZodLiteral<EventType.CUSTOM>;
        feature_id: z.ZodString;
        timestamp: z.ZodUnion<[z.ZodDate, z.ZodString]>;
        metadata: z.ZodRecord<z.core.$ZodRecordKey, z.core.SomeType>;
        idempotency_key: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>], "event_type">>;
}, z.core.$strip>;
export type TokenUsageEventInput = z.infer<typeof tokenUsageEventSchema>;
export type ImageGenerationEventInput = z.infer<typeof imageGenerationEventSchema>;
export type CustomEventInput = z.infer<typeof customEventSchema>;
export type UsageEventInput = z.infer<typeof usageEventSchema>;
export type UsageEventBatchInput = z.infer<typeof usageEventBatchSchema>;
//# sourceMappingURL=events.d.ts.map